In [1]:
# create more features

In [2]:
# imports
import pandas as pd

In [3]:
# read in master games data
master_data = pd.read_excel(r'data/master_games_data.xlsx', header=0)

# inspect
master_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3381 entries, 0 to 3380
Data columns (total 44 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Game_Link                 3381 non-null   object
 1   Extra_Time                3381 non-null   object
 2   Home_Team                 3381 non-null   object
 3   Away_Team                 3381 non-null   object
 4   Home_Score                3381 non-null   int64
 5   Away_Score                3381 non-null   int64
 6   P1_Home_Score             3381 non-null   int64
 7   P1_Away_Score             3381 non-null   int64
 8   P2_Home_Score             3381 non-null   int64
 9   P2_Away_Score             3381 non-null   int64
 10  P3_Home_Score             3381 non-null   int64
 11  P3_Away_Score             3381 non-null   int64
 12  P4_Home_Score             3381 non-null   int64
 13  P4_Away_Score             3381 non-null   int64
 14  P5_Home_Score             3381 non-null   int64
 15  P5_Away_Score             3381 non-null   int64
 16  Time                      3381 non-null   object
 17  Month_int                 3381 non-null   int64
 18  Date                      3381 non-null   datetime64[ns]
 19  Season                    3381 non-null   int64
 20  Total_Score               3381 non-null   int64
 21  Game_ID                   3381 non-null   object
 22  regular_time_score_home   3381 non-null   int64
 23  regular_time_score_away   3381 non-null   int64
 24  regular_time_score_total  3381 non-null   int64
 25  Reg_Home_Win              3381 non-null   bool
 26  Reg_Away_Win              3381 non-null   bool
 27  Reg_Tie                   3381 non-null   bool
 28  FT_Home_Win               3381 non-null   bool
 29  FT_Away_Win               3381 non-null   bool
 30  Day_of_Week               3381 non-null   object
 31  Month                     3381 non-null   object
 32  Week_of_Year              3381 non-null   int64
 33  Home_Conf                 3336 non-null   object
 34  Away_Conf                 3335 non-null   object
 35  Home_Div                  3336 non-null   object
 36  Away_Div                  3335 non-null   object
 37  Conf_Matchup              3381 non-null   bool
 38  Div_Matchup               3381 non-null   bool
 39  Conf_Pair                 3290 non-null   object
 40  Div_Pair                  3290 non-null   object
 41  Team_Pair                 3381 non-null   object
 42  Game_Start_Hour           3381 non-null   int64
 43  Start_Hour_Group          3381 non-null   object
dtypes: bool(7), datetime64[ns](1), int64(20), object(16)
memory usage: 1000.6+ KB

In [ ]:
# inspec distribution of total score
print(master_data['Total_Score'].std() ** 2)
master_data['Total_Score'].describe()

5.272494920273227

count    3381.000000
mean        6.128660
std         2.296191
min         1.000000
25%         5.000000
50%         6.000000
75%         7.000000
max        17.000000
Name: Total_Score, dtype: float64

In [6]:
# function that takes the df, sorts it by the target grain, then performs the groupby
def grain_sort_cumsum_props(home_vs_away: str, df: pd.DataFrame) -> pd.DataFrame:
    # add home or away team to sort grain
    home_plus_year = [home_vs_away, 'Season']
    
    # combine to create final sort grain
    # sort_grain = home_plus_year + ['Date', 'Game_ID']
    sort_grain = home_plus_year + ['Date']

    # sort
    df = df.sort_values(by=sort_grain)

    # hard code cumsum cols
    cum_cols = ["Reg_Home_Win", "Reg_Away_Win", "Reg_Tie", 'P1_Home_Score', 'P1_Away_Score', 
                'P2_Home_Score', 'P2_Away_Score', 'P3_Home_Score', 'P3_Away_Score',
                'regular_time_score_home', 'regular_time_score_away']
    
    # add count of games for home or away
    df[f'cum_{home_vs_away}_Games'] = df.groupby(home_plus_year).cumcount() + 1

    # compute cumsum for each group
    df[[f"cum_{col}" for col in cum_cols]] = df.groupby(home_plus_year)[cum_cols].cumsum()

    # calc prop home reg win
    df['prop_Reg_Home_Win'] = df['cum_Reg_Home_Win'] / df[f'cum_{home_vs_away}_Games']
    df['prop_Reg_Away_Win'] = df['cum_Reg_Away_Win'] / df[f'cum_{home_vs_away}_Games']
    df['prop_Reg_Tie'] = df['cum_Reg_Tie'] / df[f'cum_{home_vs_away}_Games']

    # calc props for what % of goals scored in each period
    df['prop_P1_Home_Score'] = df['cum_P1_Home_Score'] / df['cum_regular_time_score_home']
    df['prop_P2_Home_Score'] = df['cum_P2_Home_Score'] / df['cum_regular_time_score_home']
    df['prop_P3_Home_Score'] = df['cum_P3_Home_Score'] / df['cum_regular_time_score_home']

    df['prop_P1_Away_Score'] = df['cum_P1_Away_Score'] / df['cum_regular_time_score_away']
    df['prop_P2_Away_Score'] = df['cum_P2_Away_Score'] / df['cum_regular_time_score_away']
    df['prop_P3_Away_Score'] = df['cum_P3_Away_Score'] / df['cum_regular_time_score_away']

    # calc goal diffs at the period level
    df['prop_P1_Home_Goal_Diff'] = df['cum_P1_Home_Score'] / df['cum_P1_Away_Score']
    df['prop_P2_Home_Goal_Diff'] = df['cum_P2_Home_Score'] / df['cum_P2_Away_Score']
    df['prop_P3_Home_Goal_Diff'] = df['cum_P3_Home_Score'] / df['cum_P3_Away_Score']

    df['prop_P1_Away_Goal_Diff'] = df['cum_P1_Away_Score'] / df['cum_P1_Home_Score']
    df['prop_P2_Away_Goal_Diff'] = df['cum_P2_Away_Score'] / df['cum_P2_Home_Score']
    df['prop_P3_Away_Goal_Diff'] = df['cum_P3_Away_Score'] / df['cum_P3_Home_Score']

    # calc props for goals scored / allowed
    df['prop_reg_home_goal_diff'] = df['cum_regular_time_score_home'] / (df['cum_regular_time_score_home'] + df['cum_regular_time_score_away'])
    df['prop_reg_away_goal_diff'] = 1 - df['prop_reg_home_goal_diff']

    # calc avg goals per game
    df['avg_reg_home_goals_per_game'] = df['cum_regular_time_score_home'] / df[f'cum_{home_vs_away}_Games']
    df['avg_reg_away_goals_per_game'] = df['cum_regular_time_score_away'] / df[f'cum_{home_vs_away}_Games']

    # isolate cum, prop, and avg cols
    sel_cum_cols = [x for x in df.columns if x.startswith('prop_') or x.startswith('avg_')]

    # trim to final cols
    final_cols = sort_grain + sel_cum_cols
    df = df[final_cols]

    # shift feature cols down that are not in sort_grain
    df[sel_cum_cols] = df.groupby(home_plus_year)[sel_cum_cols].shift(1)

    # shift feature cols down that are not in sort_grain
    df[sel_cum_cols] = df.groupby(home_plus_year)[sel_cum_cols].shift(1)

    # rename the sel_cum_cols to indicate home vs away
    if home_vs_away == 'Home_Team':
        home_vs_away = 'Home'
    else:
        home_vs_away = 'Away'
    
    rename_dict = {col: f"{col}_{home_vs_away}" for col in sel_cum_cols}
    df = df.rename(columns=rename_dict)

    return df

# test func
all_home_games = grain_sort_cumsum_props('Home_Team', master_data)
all_home_games.info()
all_home_games.head()

<class 'pandas.core.frame.DataFrame'>
Index: 3381 entries, 1496 to 3095
Data columns (total 22 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Home_Team                         3381 non-null   object
 1   Season                            3381 non-null   int64
 2   Date                              3381 non-null   datetime64[ns]
 3   prop_Reg_Home_Win_Home            3189 non-null   float64
 4   prop_Reg_Away_Win_Home            3189 non-null   float64
 5   prop_Reg_Tie_Home                 3189 non-null   float64
 6   prop_P1_Home_Score_Home           3188 non-null   float64
 7   prop_P2_Home_Score_Home           3188 non-null   float64
 8   prop_P3_Home_Score_Home           3188 non-null   float64
 9   prop_P1_Away_Score_Home           3176 non-null   float64
 10  prop_P2_Away_Score_Home           3176 non-null   float64
 11  prop_P3_Away_Score_Home           3176 non-null   float64
 12  prop_P1_Home_Goal_Diff_Home       3173 non-null   float64
 13  prop_P2_Home_Goal_Diff_Home       3172 non-null   float64
 14  prop_P3_Home_Goal_Diff_Home       3174 non-null   float64
 15  prop_P1_Away_Goal_Diff_Home       3173 non-null   float64
 16  prop_P2_Away_Goal_Diff_Home       3172 non-null   float64
 17  prop_P3_Away_Goal_Diff_Home       3174 non-null   float64
 18  prop_reg_home_goal_diff_Home      3189 non-null   float64
 19  prop_reg_away_goal_diff_Home      3189 non-null   float64
 20  avg_reg_home_goals_per_game_Home  3189 non-null   float64
 21  avg_reg_away_goals_per_game_Home  3189 non-null   float64
dtypes: datetime64[ns](1), float64(19), int64(1), object(1)
memory usage: 607.5+ KB

,Home_Team,Season,Date,prop_Reg_Home_Win_Home,prop_Reg_Away_Win_Home,prop_Reg_Tie_Home,prop_P1_Home_Score_Home,prop_P2_Home_Score_Home,prop_P3_Home_Score_Home,prop_P1_Away_Score_Home,...,prop_P1_Home_Goal_Diff_Home,prop_P2_Home_Goal_Diff_Home,prop_P3_Home_Goal_Diff_Home,prop_P1_Away_Goal_Diff_Home,prop_P2_Away_Goal_Diff_Home,prop_P3_Away_Goal_Diff_Home,prop_reg_home_goal_diff_Home,prop_reg_away_goal_diff_Home,avg_reg_home_goals_per_game_Home,avg_reg_away_goals_per_game_Home
1496,Anaheim Ducks,2023,2023-09-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1471,Anaheim Ducks,2023,2023-09-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1457,Anaheim Ducks,2023,2023-09-29,0.000000,0.000000,1.000000,0.500000,0.000000,0.500000,0.00,...,inf,0.0,1.0,0.000000,inf,1.000000,0.500000,0.500000,2.0,2.000000
1413,Anaheim Ducks,2023,2023-10-05,0.500000,0.000000,0.500000,0.500000,0.166667,0.333333,0.25,...,3.0,1.0,1.0,0.333333,1.0,1.000000,0.600000,0.400000,3.0,2.000000
1366,Anaheim Ducks,2023,2023-10-15,0.333333,0.333333,0.333333,0.444444,0.222222,0.333333,0.50,...,1.0,1.0,1.5,1.000000,1.0,0.666667,0.529412,0.470588,3.0,2.666667

In [7]:
# repeat for away teams
all_away_games = grain_sort_cumsum_props('Away_Team', master_data)
all_away_games.info()
all_away_games.head()

<class 'pandas.core.frame.DataFrame'>
Index: 3381 entries, 1480 to 3014
Data columns (total 22 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Away_Team                         3381 non-null   object
 1   Season                            3381 non-null   int64
 2   Date                              3381 non-null   datetime64[ns]
 3   prop_Reg_Home_Win_Away            3189 non-null   float64
 4   prop_Reg_Away_Win_Away            3189 non-null   float64
 5   prop_Reg_Tie_Away                 3189 non-null   float64
 6   prop_P1_Home_Score_Away           3187 non-null   float64
 7   prop_P2_Home_Score_Away           3187 non-null   float64
 8   prop_P3_Home_Score_Away           3187 non-null   float64
 9   prop_P1_Away_Score_Away           3179 non-null   float64
 10  prop_P2_Away_Score_Away           3179 non-null   float64
 11  prop_P3_Away_Score_Away           3179 non-null   float64
 12  prop_P1_Home_Goal_Diff_Away       3174 non-null   float64
 13  prop_P2_Home_Goal_Diff_Away       3170 non-null   float64
 14  prop_P3_Home_Goal_Diff_Away       3171 non-null   float64
 15  prop_P1_Away_Goal_Diff_Away       3174 non-null   float64
 16  prop_P2_Away_Goal_Diff_Away       3170 non-null   float64
 17  prop_P3_Away_Goal_Diff_Away       3171 non-null   float64
 18  prop_reg_home_goal_diff_Away      3189 non-null   float64
 19  prop_reg_away_goal_diff_Away      3189 non-null   float64
 20  avg_reg_home_goals_per_game_Away  3189 non-null   float64
 21  avg_reg_away_goals_per_game_Away  3189 non-null   float64
dtypes: datetime64[ns](1), float64(19), int64(1), object(1)
memory usage: 607.5+ KB

,Away_Team,Season,Date,prop_Reg_Home_Win_Away,prop_Reg_Away_Win_Away,prop_Reg_Tie_Away,prop_P1_Home_Score_Away,prop_P2_Home_Score_Away,prop_P3_Home_Score_Away,prop_P1_Away_Score_Away,...,prop_P1_Home_Goal_Diff_Away,prop_P2_Home_Goal_Diff_Away,prop_P3_Home_Goal_Diff_Away,prop_P1_Away_Goal_Diff_Away,prop_P2_Away_Goal_Diff_Away,prop_P3_Away_Goal_Diff_Away,prop_reg_home_goal_diff_Away,prop_reg_away_goal_diff_Away,avg_reg_home_goals_per_game_Away,avg_reg_away_goals_per_game_Away
1480,Anaheim Ducks,2023,2023-09-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1445,Anaheim Ducks,2023,2023-10-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1430,Anaheim Ducks,2023,2023-10-03,0.000000,1.000000,0.0,0.0,0.500000,0.500000,0.750000,...,0.0,inf,1.000000,inf,0.0,1.0,0.333333,0.666667,2.000000,4.000000
1404,Anaheim Ducks,2023,2023-10-07,0.000000,1.000000,0.0,0.5,0.333333,0.166667,0.555556,...,0.6,2.0,0.333333,1.666667,0.5,3.0,0.400000,0.600000,3.000000,4.500000
1371,Anaheim Ducks,2023,2023-10-14,0.333333,0.666667,0.0,0.6,0.200000,0.200000,0.500000,...,1.2,1.0,0.666667,0.833333,1.0,1.5,0.500000,0.500000,3.333333,3.333333

In [ ]:
# # sort by Home then away then date and get cum avgs
# def h2h_grain_sort_cumsum_props(df: pd.DataFrame) -> pd.DataFrame:
#     # add home or away team to sort grain
#     home_plus_year = ['Home_Team', 'Away_Team', 'Season']
    
#     # combine to create final sort grain
#     sort_grain = home_plus_year + ['Date']

#     # sort
#     df = df.sort_values(by=sort_grain)

#     # hard code cumsum cols
#     cum_cols = ["Reg_Home_Win", "Reg_Away_Win", "Reg_Tie", 'P1_Home_Score', 'P1_Away_Score', 
#                 'P2_Home_Score', 'P2_Away_Score', 'P3_Home_Score', 'P3_Away_Score',
#                 'regular_time_score_home', 'regular_time_score_away']
    
#     # add count of games for home or away
#     df[f'cum_Games'] = df.groupby(home_plus_year).cumcount() + 1

#     # compute cumsum for each group
#     df[[f"cum_{col}" for col in cum_cols]] = df.groupby(home_plus_year)[cum_cols].cumsum()

#     # calc prop home reg win
#     df['prop_Reg_Home_Win'] = df['cum_Reg_Home_Win'] / df[f'cum_Games']
#     df['prop_Reg_Away_Win'] = df['cum_Reg_Away_Win'] / df[f'cum_Games']
#     df['prop_Reg_Tie'] = df['cum_Reg_Tie'] / df[f'cum_Games']

#     # calc props for what % of goals scored in each period
#     df['prop_P1_Home_Score'] = df['cum_P1_Home_Score'] / df['cum_regular_time_score_home']
#     df['prop_P2_Home_Score'] = df['cum_P2_Home_Score'] / df['cum_regular_time_score_home']
#     df['prop_P3_Home_Score'] = df['cum_P3_Home_Score'] / df['cum_regular_time_score_home']

#     df['prop_P1_Away_Score'] = df['cum_P1_Away_Score'] / df['cum_regular_time_score_away']
#     df['prop_P2_Away_Score'] = df['cum_P2_Away_Score'] / df['cum_regular_time_score_away']
#     df['prop_P3_Away_Score'] = df['cum_P3_Away_Score'] / df['cum_regular_time_score_away']

#     # calc goal diffs at the period level
#     df['prop_P1_Home_Goal_Diff'] = df['cum_P1_Home_Score'] / df['cum_P1_Away_Score']
#     df['prop_P2_Home_Goal_Diff'] = df['cum_P2_Home_Score'] / df['cum_P2_Away_Score']
#     df['prop_P3_Home_Goal_Diff'] = df['cum_P3_Home_Score'] / df['cum_P3_Away_Score']

#     df['prop_P1_Away_Goal_Diff'] = df['cum_P1_Away_Score'] / df['cum_P1_Home_Score']
#     df['prop_P2_Away_Goal_Diff'] = df['cum_P2_Away_Score'] / df['cum_P2_Home_Score']
#     df['prop_P3_Away_Goal_Diff'] = df['cum_P3_Away_Score'] / df['cum_P3_Home_Score']

#     # calc props for goals scored / allowed
#     df['prop_reg_home_goal_diff'] = df['cum_regular_time_score_home'] / (df['cum_regular_time_score_home'] + df['cum_regular_time_score_away'])
#     df['prop_reg_away_goal_diff'] = 1 - df['prop_reg_home_goal_diff']

#     # calc avg goals per game
#     df['avg_reg_home_goals_per_game'] = df['cum_regular_time_score_home'] / df[f'cum_Games']
#     df['avg_reg_away_goals_per_game'] = df['cum_regular_time_score_away'] / df[f'cum_Games']

#     # isolate cum, prop, and avg cols
#     sel_cum_cols = [x for x in df.columns if x.startswith('prop_') or x.startswith('avg_')]

#     # trim to final cols
#     final_cols = sort_grain + sel_cum_cols
#     df = df[final_cols]

#     # shift feature cols down that are not in sort_grain
#     df[sel_cum_cols] = df.groupby(home_plus_year)[sel_cum_cols].shift(1)
    
#     rename_dict = {col: f"{col}_H2H" for col in sel_cum_cols}
#     df = df.rename(columns=rename_dict)

#     return df

# # test func
# h2h_cum_df = h2h_grain_sort_cumsum_props(master_data)
# h2h_cum_df.info()
# h2h_cum_df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 3381 entries, 1413 to 1777
Data columns (total 23 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Home_Team                        3381 non-null   object
 1   Away_Team                        3381 non-null   object
 2   Season                           3381 non-null   int64
 3   Date                             3381 non-null   datetime64[ns]
 4   prop_Reg_Home_Win_H2H            1074 non-null   float64
 5   prop_Reg_Away_Win_H2H            1074 non-null   float64
 6   prop_Reg_Tie_H2H                 1074 non-null   float64
 7   prop_P1_Home_Score_H2H           1049 non-null   float64
 8   prop_P2_Home_Score_H2H           1049 non-null   float64
 9   prop_P3_Home_Score_H2H           1049 non-null   float64
 10  prop_P1_Away_Score_H2H           1026 non-null   float64
 11  prop_P2_Away_Score_H2H           1026 non-null   float64
 12  prop_P3_Away_Score_H2H           1026 non-null   float64
 13  prop_P1_Home_Goal_Diff_H2H       943 non-null    float64
 14  prop_P2_Home_Goal_Diff_H2H       976 non-null    float64
 15  prop_P3_Home_Goal_Diff_H2H       976 non-null    float64
 16  prop_P1_Away_Goal_Diff_H2H       943 non-null    float64
 17  prop_P2_Away_Goal_Diff_H2H       976 non-null    float64
 18  prop_P3_Away_Goal_Diff_H2H       976 non-null    float64
 19  prop_reg_home_goal_diff_H2H      1072 non-null   float64
 20  prop_reg_away_goal_diff_H2H      1072 non-null   float64
 21  avg_reg_home_goals_per_game_H2H  1074 non-null   float64
 22  avg_reg_away_goals_per_game_H2H  1074 non-null   float64
dtypes: datetime64[ns](1), float64(19), int64(1), object(2)
memory usage: 633.9+ KB

,Home_Team,Away_Team,Season,Date,prop_Reg_Home_Win_H2H,prop_Reg_Away_Win_H2H,prop_Reg_Tie_H2H,prop_P1_Home_Score_H2H,prop_P2_Home_Score_H2H,prop_P3_Home_Score_H2H,...,prop_P1_Home_Goal_Diff_H2H,prop_P2_Home_Goal_Diff_H2H,prop_P3_Home_Goal_Diff_H2H,prop_P1_Away_Goal_Diff_H2H,prop_P2_Away_Goal_Diff_H2H,prop_P3_Away_Goal_Diff_H2H,prop_reg_home_goal_diff_H2H,prop_reg_away_goal_diff_H2H,avg_reg_home_goals_per_game_H2H,avg_reg_away_goals_per_game_H2H
1413,Anaheim Ducks,Arizona Coyotes,2023,2023-10-05,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1256,Anaheim Ducks,Arizona Coyotes,2023,2023-11-01,0.0,1.0,0.0,0.0,0.0,1.0,...,NaN,0.0,1.0,NaN,inf,1.000000,0.333333,0.666667,2.0,4.0
846,Anaheim Ducks,Arizona Coyotes,2023,2023-12-29,0.0,0.5,0.5,0.4,0.0,0.6,...,1.0,0.0,1.5,1.0,inf,0.666667,0.416667,0.583333,2.5,3.5
1319,Anaheim Ducks,Boston Bruins,2023,2023-10-22,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1768,Anaheim Ducks,Boston Bruins,2024,2025-03-26,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# get key cols from master data
base_cols = ['Date', 'Season', 'Game_ID', 'Home_Team', 'Away_Team',
    'Total_Score', 'Month', 'Day_of_Week', 'Conf_Matchup', 'Div_Matchup', 
    'Conf_Pair', 'Div_Pair', 'Team_Pair'
    ]

# comment out for now 'Reg_Home_Win', 'Reg_Away_Win', 'Reg_Tie',

modeling_data_base = master_data[base_cols]

# ensure data sorted correctly
modeling_data = modeling_data_base.sort_values(by=['Home_Team', 'Season', 'Date'])

# join home and away dfs to modeling data
modeling_data = modeling_data.merge(all_home_games, how='left', on=['Home_Team', 'Season', 'Date'])
modeling_data = modeling_data.merge(all_away_games, how='left', on=['Away_Team', 'Season', 'Date'])

# # join in h2h data
# modeling_data = modeling_data.merge(h2h_cum_df, how='left', on=['Home_Team', 'Away_Team', 'Season', 'Date'])

# inspect
modeling_data.info()
modeling_data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3405 entries, 0 to 3404
Data columns (total 51 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Date                              3405 non-null   datetime64[ns]
 1   Season                            3405 non-null   int64
 2   Game_ID                           3405 non-null   object
 3   Home_Team                         3405 non-null   object
 4   Away_Team                         3405 non-null   object
 5   Total_Score                       3405 non-null   int64
 6   Month                             3405 non-null   object
 7   Day_of_Week                       3405 non-null   object
 8   Conf_Matchup                      3405 non-null   bool
 9   Div_Matchup                       3405 non-null   bool
 10  Conf_Pair                         3310 non-null   object
 11  Div_Pair                          3310 non-null   object
 12  Team_Pair                         3405 non-null   object
 13  prop_Reg_Home_Win_Home            3190 non-null   float64
 14  prop_Reg_Away_Win_Home            3190 non-null   float64
 15  prop_Reg_Tie_Home                 3190 non-null   float64
 16  prop_P1_Home_Score_Home           3189 non-null   float64
 17  prop_P2_Home_Score_Home           3189 non-null   float64
 18  prop_P3_Home_Score_Home           3189 non-null   float64
 19  prop_P1_Away_Score_Home           3177 non-null   float64
 20  prop_P2_Away_Score_Home           3177 non-null   float64
 21  prop_P3_Away_Score_Home           3177 non-null   float64
 22  prop_P1_Home_Goal_Diff_Home       3174 non-null   float64
 23  prop_P2_Home_Goal_Diff_Home       3173 non-null   float64
 24  prop_P3_Home_Goal_Diff_Home       3175 non-null   float64
 25  prop_P1_Away_Goal_Diff_Home       3174 non-null   float64
 26  prop_P2_Away_Goal_Diff_Home       3173 non-null   float64
 27  prop_P3_Away_Goal_Diff_Home       3175 non-null   float64
 28  prop_reg_home_goal_diff_Home      3190 non-null   float64
 29  prop_reg_away_goal_diff_Home      3190 non-null   float64
 30  avg_reg_home_goals_per_game_Home  3190 non-null   float64
 31  avg_reg_away_goals_per_game_Home  3190 non-null   float64
 32  prop_Reg_Home_Win_Away            3190 non-null   float64
 33  prop_Reg_Away_Win_Away            3190 non-null   float64
 34  prop_Reg_Tie_Away                 3190 non-null   float64
 35  prop_P1_Home_Score_Away           3188 non-null   float64
 36  prop_P2_Home_Score_Away           3188 non-null   float64
 37  prop_P3_Home_Score_Away           3188 non-null   float64
 38  prop_P1_Away_Score_Away           3180 non-null   float64
 39  prop_P2_Away_Score_Away           3180 non-null   float64
 40  prop_P3_Away_Score_Away           3180 non-null   float64
 41  prop_P1_Home_Goal_Diff_Away       3175 non-null   float64
 42  prop_P2_Home_Goal_Diff_Away       3171 non-null   float64
 43  prop_P3_Home_Goal_Diff_Away       3172 non-null   float64
 44  prop_P1_Away_Goal_Diff_Away       3175 non-null   float64
 45  prop_P2_Away_Goal_Diff_Away       3171 non-null   float64
 46  prop_P3_Away_Goal_Diff_Away       3172 non-null   float64
 47  prop_reg_home_goal_diff_Away      3190 non-null   float64
 48  prop_reg_away_goal_diff_Away      3190 non-null   float64
 49  avg_reg_home_goals_per_game_Away  3190 non-null   float64
 50  avg_reg_away_goals_per_game_Away  3190 non-null   float64
dtypes: bool(2), datetime64[ns](1), float64(38), int64(2), object(8)
memory usage: 1.3+ MB

,Date,Season,Game_ID,Home_Team,Away_Team,Total_Score,Month,Day_of_Week,Conf_Matchup,Div_Matchup,...,prop_P1_Home_Goal_Diff_Away,prop_P2_Home_Goal_Diff_Away,prop_P3_Home_Goal_Diff_Away,prop_P1_Away_Goal_Diff_Away,prop_P2_Away_Goal_Diff_Away,prop_P3_Away_Goal_Diff_Away,prop_reg_home_goal_diff_Away,prop_reg_away_goal_diff_Away,avg_reg_home_goals_per_game_Away,avg_reg_away_goals_per_game_Away
0,2023-09-24,2023,2023-09-24-20:00|Anaheim Ducks vs Los Angeles ...,Anaheim Ducks,Los Angeles Kings,5,September,Sunday,True,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023-09-27,2023,2023-09-27-22:00|Anaheim Ducks vs San Jose Sharks,Anaheim Ducks,San Jose Sharks,6,September,Wednesday,True,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023-09-29,2023,2023-09-29-22:00|Anaheim Ducks vs Los Angeles ...,Anaheim Ducks,Los Angeles Kings,7,September,Friday,True,True,...,inf,1.0,2.000000,0.00,1.0,0.5,0.583333,0.416667,3.500000,2.500000
3,2023-10-05,2023,2023-10-05-22:00|Anaheim Ducks vs Arizona Coyotes,Anaheim Ducks,Arizona Coyotes,6,October,Thursday,False,False,...,2.0,inf,1.666667,0.50,0.0,0.6,0.764706,0.235294,4.333333,1.333333
4,2023-10-15,2023,2023-10-15-20:30|Anaheim Ducks vs Carolina Hur...,Anaheim Ducks,Carolina Hurricanes,9,October,Sunday,False,False,...,4.0,inf,2.500000,0.25,0.0,0.4,0.812500,0.187500,4.333333,1.000000

In [9]:
# write final modeling data to excel
modeling_data.to_excel(r'data/modeling_data.xlsx', index=False)

In [15]:
# Note that most NHL teams play 3-5 games per week