In [1]:
# union all 1x2_odds files together and join to master data

In [2]:
# imports
import pandas as pd

In [3]:
# get 1x2 odds data for last few years
games_0 = pd.read_excel('data/2023_1x2_data.xlsx', header=0)
games_1 = pd.read_excel('data/2024_1x2_data.xlsx', header=0)
games_2 = pd.read_excel('data/2025_1x2_data.xlsx', header=0)

# union together
all_1x2_odds = pd.concat([games_0, games_1, games_2], ignore_index=True)

# reset index
all_1x2_odds.reset_index(drop=True, inplace=True)

# only keep key cols
key_cols = ['Game_Link'] + [x for x in all_1x2_odds.columns if x.startswith('Odds')]
all_1x2_odds = all_1x2_odds[key_cols]

# inspect
all_1x2_odds.info()
all_1x2_odds.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3381 entries, 0 to 3380
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Game_Link  3381 non-null   object
 1   Odds_1     3256 non-null   float64
 2   Odds_X     3256 non-null   float64
 3   Odds_2     3256 non-null   float64
dtypes: float64(3), object(1)
memory usage: 105.8+ KB

                                           Game_Link  Odds_1  Odds_X  Odds_2
0  https://www.flashscore.com/match/hockey/edmont...    2.45     4.0    2.45
1  https://www.flashscore.com/match/hockey/edmont...    2.35     4.0    2.55
2  https://www.flashscore.com/match/hockey/edmont...    2.00     4.0    3.10
3  https://www.flashscore.com/match/hockey/edmont...    2.30     4.0    2.55
4  https://www.flashscore.com/match/hockey/edmont...    2.15     4.0    2.80

In [4]:
# read in master games data
all_games = pd.read_excel(r'data/master_games_data.xlsx', header=0)

# inspect
all_games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3381 entries, 0 to 3380
Data columns (total 43 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Game_Link                 3381 non-null   object
 1   Extra_Time                3381 non-null   object
 2   Home_Team                 3381 non-null   object
 3   Away_Team                 3381 non-null   object
 4   Home_Score                3381 non-null   int64
 5   Away_Score                3381 non-null   int64
 6   P1_Home_Score             3381 non-null   int64
 7   P1_Away_Score             3381 non-null   int64
 8   P2_Home_Score             3381 non-null   int64
 9   P2_Away_Score             3381 non-null   int64
 10  P3_Home_Score             3381 non-null   int64
 11  P3_Away_Score             3381 non-null   int64
 12  P4_Home_Score             3381 non-null   int64
 13  P4_Away_Score             3381 non-null   int64
 14  P5_Home_Score             3381 non-null   int64
 15  P5_Away_Score             3381 non-null   int64
 16  Time                      3381 non-null   object
 17  Month_int                 3381 non-null   int64
 18  Date                      3381 non-null   datetime64[ns]
 19  Season                    3381 non-null   int64
 20  Total_Score               3381 non-null   int64
 21  Game_ID                   3381 non-null   object
 22  regular_time_score_home   3381 non-null   int64
 23  regular_time_score_away   3381 non-null   int64
 24  regular_time_score_total  3381 non-null   int64
 25  Reg_Home_Win              3381 non-null   bool
 26  Reg_Away_Win              3381 non-null   bool
 27  Reg_Tie                   3381 non-null   bool
 28  FT_Home_Win               3381 non-null   bool
 29  FT_Away_Win               3381 non-null   bool
 30  Day_of_Week               3381 non-null   object
 31  Month                     3381 non-null   object
 32  Week_of_Year              3381 non-null   int64
 33  Home_Conf                 3336 non-null   object
 34  Away_Conf                 3335 non-null   object
 35  Home_Div                  3336 non-null   object
 36  Away_Div                  3335 non-null   object
 37  Conf_Matchup              3381 non-null   bool
 38  Div_Matchup               3381 non-null   bool
 39  Conf_Pair                 3290 non-null   object
 40  Div_Pair                  3290 non-null   object
 41  Team_Pair                 3381 non-null   object
 42  Game_Start_Hour           3381 non-null   int64
dtypes: bool(7), datetime64[ns](1), int64(20), object(15)
memory usage: 974.1+ KB

In [5]:
# join the 2 dfs together
master_data = pd.merge(all_games, all_1x2_odds, how='left', on='Game_Link')

# inspect
master_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3381 entries, 0 to 3380
Data columns (total 46 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Game_Link                 3381 non-null   object
 1   Extra_Time                3381 non-null   object
 2   Home_Team                 3381 non-null   object
 3   Away_Team                 3381 non-null   object
 4   Home_Score                3381 non-null   int64
 5   Away_Score                3381 non-null   int64
 6   P1_Home_Score             3381 non-null   int64
 7   P1_Away_Score             3381 non-null   int64
 8   P2_Home_Score             3381 non-null   int64
 9   P2_Away_Score             3381 non-null   int64
 10  P3_Home_Score             3381 non-null   int64
 11  P3_Away_Score             3381 non-null   int64
 12  P4_Home_Score             3381 non-null   int64
 13  P4_Away_Score             3381 non-null   int64
 14  P5_Home_Score             3381 non-null   int64
 15  P5_Away_Score             3381 non-null   int64
 16  Time                      3381 non-null   object
 17  Month_int                 3381 non-null   int64
 18  Date                      3381 non-null   datetime64[ns]
 19  Season                    3381 non-null   int64
 20  Total_Score               3381 non-null   int64
 21  Game_ID                   3381 non-null   object
 22  regular_time_score_home   3381 non-null   int64
 23  regular_time_score_away   3381 non-null   int64
 24  regular_time_score_total  3381 non-null   int64
 25  Reg_Home_Win              3381 non-null   bool
 26  Reg_Away_Win              3381 non-null   bool
 27  Reg_Tie                   3381 non-null   bool
 28  FT_Home_Win               3381 non-null   bool
 29  FT_Away_Win               3381 non-null   bool
 30  Day_of_Week               3381 non-null   object
 31  Month                     3381 non-null   object
 32  Week_of_Year              3381 non-null   int64
 33  Home_Conf                 3336 non-null   object
 34  Away_Conf                 3335 non-null   object
 35  Home_Div                  3336 non-null   object
 36  Away_Div                  3335 non-null   object
 37  Conf_Matchup              3381 non-null   bool
 38  Div_Matchup               3381 non-null   bool
 39  Conf_Pair                 3290 non-null   object
 40  Div_Pair                  3290 non-null   object
 41  Team_Pair                 3381 non-null   object
 42  Game_Start_Hour           3381 non-null   int64
 43  Odds_1                    3256 non-null   float64
 44  Odds_X                    3256 non-null   float64
 45  Odds_2                    3256 non-null   float64
dtypes: bool(7), datetime64[ns](1), float64(3), int64(20), object(15)
memory usage: 1.0+ MB

In [6]:
# TODO - perform EDA on records that resulted in a regular time tie and see if there's any patterns or trends in this subset that could be indicative of predictive features
master_data[master_data['Reg_Tie'] == True].describe()

,Home_Score,Away_Score,P1_Home_Score,P1_Away_Score,P2_Home_Score,P2_Away_Score,P3_Home_Score,P3_Away_Score,P4_Home_Score,P4_Away_Score,...,Season,Total_Score,regular_time_score_home,regular_time_score_away,regular_time_score_total,Week_of_Year,Game_Start_Hour,Odds_1,Odds_X,Odds_2
count,714.000000,714.000000,714.000000,714.000000,714.000000,714.000000,714.000000,714.000000,714.000000,714.000000,...,714.000000,714.000000,714.000000,714.000000,714.000000,714.000000,714.000000,686.000000,686.000000,686.000000
mean,3.137255,3.075630,0.809524,0.810924,0.924370,0.911765,0.872549,0.883754,0.385154,0.334734,...,2023.694678,6.212885,2.606443,2.606443,5.212885,28.043417,19.222689,2.322996,4.292580,2.900809
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,2023.000000,1.000000,0.000000,0.000000,0.000000,1.000000,8.000000,1.290000,3.800000,1.380000
25%,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,2023.000000,5.000000,2.000000,2.000000,4.000000,10.000000,19.000000,1.840000,4.100000,2.250000
50%,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,...,2024.000000,7.000000,3.000000,3.000000,6.000000,39.000000,19.000000,2.175000,4.225000,2.700000
75%,4.000000,4.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,2024.000000,7.000000,3.000000,3.000000,6.000000,45.000000,21.000000,2.625000,4.425000,3.300000
max,8.000000,7.000000,5.000000,4.000000,4.000000,4.000000,5.000000,5.000000,1.000000,1.000000,...,2025.000000,15.000000,7.000000,7.000000,14.000000,52.000000,22.000000,6.125000,6.000000,8.500000
std,1.246903,1.277662,0.823988,0.828553,0.881408,0.873035,0.866553,0.845209,0.486973,0.472228,...,0.689980,2.318788,1.159394,1.159394,2.318788,18.216543,2.246890,0.666261,0.292265,0.920375

In [13]:
# get league avg tie prop
tie_prop = master_data[['Season', 'Reg_Tie']].value_counts().sort_index()
tie_prop

Season  Reg_Tie
2023    False      1199
        True        312
2024    False      1194
        True        308
2025    False       274
        True         94
Name: count, dtype: int64

In [ ]:
# repeat for away teams
all_away_games = grain_sort_cumsum_props('Away_Team', master_data)
all_away_games.info()
all_away_games.head()

In [15]:
# get key cols from master data
base_cols = ['Date', 'Season', 'Game_ID', 'Home_Team', 'Away_Team',
    'Odds_1', 'Odds_X', 'Odds_2', 'Reg_Tie',
    'Month', 'Day_of_Week', 'Conf_Matchup', 'Div_Matchup', 'Conf_Pair', 'Div_Pair',
    'Team_Pair'
    ]

modeling_data_base = master_data[base_cols]

# ensure data sorted correctly
modeling_data = modeling_data_base.sort_values(by=['Season', 'Date', 'Game_ID'])

# inspect
modeling_data.info()
modeling_data.head()

<class 'pandas.core.frame.DataFrame'>
Index: 3381 entries, 1510 to 3014
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          3381 non-null   datetime64[ns]
 1   Season        3381 non-null   int64
 2   Game_ID       3381 non-null   object
 3   Home_Team     3381 non-null   object
 4   Away_Team     3381 non-null   object
 5   Odds_1        3256 non-null   float64
 6   Odds_X        3256 non-null   float64
 7   Odds_2        3256 non-null   float64
 8   Reg_Tie       3381 non-null   bool
 9   Month         3381 non-null   object
 10  Day_of_Week   3381 non-null   object
 11  Conf_Matchup  3381 non-null   bool
 12  Div_Matchup   3381 non-null   bool
 13  Conf_Pair     3290 non-null   object
 14  Div_Pair      3290 non-null   object
 15  Team_Pair     3381 non-null   object
dtypes: bool(3), datetime64[ns](1), float64(3), int64(1), object(8)
memory usage: 379.7+ KB

,Date,Season,Game_ID,Home_Team,Away_Team,Odds_1,Odds_X,Odds_2,Reg_Tie,Month,Day_of_Week,Conf_Matchup,Div_Matchup,Conf_Pair,Div_Pair,Team_Pair
1510,2023-09-23,2023,2023-09-23-00:05|Arizona Coyotes vs Los Angele...,Arizona Coyotes,Los Angeles Kings,NaN,NaN,NaN,False,September,Saturday,False,False,NaN,NaN,Arizona Coyotes vs Los Angeles Kings
1509,2023-09-23,2023,2023-09-23-15:00|St. Louis Blues vs Arizona Co...,St. Louis Blues,Arizona Coyotes,NaN,NaN,NaN,False,September,Saturday,False,False,NaN,NaN,St. Louis Blues vs Arizona Coyotes
1508,2023-09-23,2023,2023-09-23-20:00|Arizona Coyotes vs St. Louis ...,Arizona Coyotes,St. Louis Blues,NaN,NaN,NaN,False,September,Saturday,False,False,NaN,NaN,Arizona Coyotes vs St. Louis Blues
1507,2023-09-24,2023,2023-09-24-00:05|Los Angeles Kings vs Arizona ...,Los Angeles Kings,Arizona Coyotes,NaN,NaN,NaN,False,September,Sunday,False,False,NaN,NaN,Los Angeles Kings vs Arizona Coyotes
1506,2023-09-24,2023,2023-09-24-13:00|Pittsburgh Penguins vs Columb...,Pittsburgh Penguins,Columbus Blue Jackets,NaN,NaN,NaN,True,September,Sunday,True,True,Eastern-Eastern,Metropolitan-Metropolitan,Pittsburgh Penguins vs Columbus Blue Jackets

In [16]:
# write final modeling data to excel
modeling_data.to_excel(r'data/modeling_data.xlsx', index=False)

In [ ]:
# Note that most NHL teams play 3-5 games per week